# Generated by Django 4.1.1 on 2023-06-16 06:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
