# Generated by Django 4.1.1 on 2023-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_social_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='link',
        ),
    ]
