# Generated by Django 4.1.1 on 2023-06-14 16:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_post_images_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, choices=[('0', 'Select Category'), ('1', 'Web Development'), ('2', 'Mobile Development'), ('3', 'Desktop Development'), ('4', 'Machine Learning'), ('5', 'Data Science'), ('6', 'Artificial Intelligence'), ('7', 'Cloud Computing'), ('8', 'DevOps'), ('9', 'Cyber Security'), ('10', 'Game Development'), ('11', 'Robotics'), ('12', 'Internet of Things'), ('13', 'Blockchain'), ('14', 'Augmented Reality'), ('15', 'Virtual Reality'), ('16', 'Mixed Reality'), ('17', 'Quantum Computing'), ('18', 'Big Data'), ('19', 'Other')], default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='framework',
            field=models.CharField(blank=True, choices=[('0', 'Select Framework'), ('1', 'Django'), ('2', 'Flask'), ('3', 'React'), ('4', 'Angular'), ('5', 'Vue'), ('6', 'Laravel'), ('7', 'Spring'), ('8', 'Express'), ('9', 'Django Rest Framework'), ('10', 'Flutter'), ('11', 'React Native'), ('12', 'Ionic'), ('13', 'Xamarin'), ('14', 'Electron'), ('15', 'Other')], default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Post Summary'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('0', 'Select Tag'), ('1', 'Python'), ('2', 'Java'), ('3', 'C++'), ('4', 'C#'), ('5', 'JavaScript'), ('6', 'PHP'), ('7', 'Swift'), ('8', 'Kotlin'), ('9', 'Dart'), ('10', 'Ruby'), ('11', 'Go'), ('12', 'R'), ('13', 'Scala'), ('14', 'Rust'), ('15', 'TypeScript'), ('16', 'SQL'), ('17', 'HTML'), ('18', 'CSS'), ('19', 'React'), ('20', 'Tailwind CSS'), ('21', 'MongoDB'), ('22', 'Artificial Intelligence'), ('23', 'Machine Learning'), ('24', 'Deep Learning'), ('25', 'Data Science'), ('26', 'Big Data'), ('27', 'Cloud Computing'), ('28', 'DevOps'), ('29', 'Blockchain'), ('30', 'Internet of Things (IoT)'), ('31', 'Virtual Reality (VR)'), ('32', 'Augmented Reality (AR)'), ('33', 'Cybersecurity'), ('34', 'Responsive Web Design'), ('35', 'Progressive Web Apps (PWA)'), ('36', 'Microservices'), ('37', 'Serverless Architecture'), ('38', 'Containerization'), ('39', 'Git'), ('40', 'Jenkins'), ('41', 'Docker'), ('42', 'Kubernetes'), ('43', 'Amazon Web Services (AWS)'), ('44', 'Microsoft Azure'), ('45', 'Google Cloud Platform (GCP)'), ('46', 'WordPress'), ('47', 'Drupal'), ('48', 'Joomla'), ('49', 'Magento'), ('50', 'Salesforce')], default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Compose Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='draft', max_length=10),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
