# Generated by Django 4.1.1 on 2023-06-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_description_remove_category_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='technologies',
        ),
    ]
