# Generated by Django 4.1.1 on 2023-06-14 19:14

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_images_remove_project_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='framework',
        ),
        migrations.AddField(
            model_name='post',
            name='frameworks',
            field=core.models.CustomMultiSelectField(blank=True, choices=[('1', 'Django'), ('2', 'Flask'), ('3', 'React'), ('4', 'Angular'), ('5', 'Vue'), ('6', 'Laravel'), ('7', 'Spring'), ('8', 'Express'), ('9', 'Django Rest Framework'), ('10', 'Flutter'), ('11', 'React Native'), ('12', 'Ionic'), ('13', 'Xamarin'), ('14', 'Electron'), ('15', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=core.models.CustomMultiSelectField(blank=True, choices=[('0', 'Full Stack Development'), ('1', 'Web Development'), ('2', 'Mobile Development'), ('3', 'Desktop Development'), ('4', 'Machine Learning'), ('5', 'Data Science'), ('6', 'Artificial Intelligence'), ('7', 'Cloud Computing'), ('8', 'DevOps'), ('9', 'Cyber Security'), ('10', 'Game Development'), ('11', 'Robotics'), ('12', 'Internet of Things'), ('13', 'Blockchain'), ('14', 'Augmented Reality'), ('15', 'Virtual Reality'), ('16', 'Mixed Reality'), ('17', 'Quantum Computing'), ('18', 'Big Data'), ('19', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=core.models.CustomMultiSelectField(blank=True, choices=[('0', 'C'), ('1', 'Python'), ('2', 'Java'), ('3', 'C++'), ('4', 'C#'), ('5', 'JavaScript'), ('6', 'PHP'), ('7', 'Swift'), ('8', 'Kotlin'), ('9', 'Dart'), ('10', 'Ruby'), ('11', 'Go'), ('12', 'R'), ('13', 'Scala'), ('14', 'Rust'), ('15', 'TypeScript'), ('16', 'SQL'), ('17', 'HTML'), ('18', 'CSS'), ('19', 'React'), ('20', 'Tailwind CSS'), ('21', 'MongoDB'), ('22', 'Artificial Intelligence'), ('23', 'Machine Learning'), ('24', 'Deep Learning'), ('25', 'Data Science'), ('26', 'Big Data'), ('27', 'Cloud Computing'), ('28', 'DevOps'), ('29', 'Blockchain'), ('30', 'Internet of Things (IoT)'), ('31', 'Virtual Reality (VR)'), ('32', 'Augmented Reality (AR)'), ('33', 'Cybersecurity'), ('34', 'Responsive Web Design'), ('35', 'Progressive Web Apps (PWA)'), ('36', 'Microservices'), ('37', 'Serverless Architecture'), ('38', 'Containerization'), ('39', 'Git'), ('40', 'Jenkins'), ('41', 'Docker'), ('42', 'Kubernetes'), ('43', 'Amazon Web Services (AWS)'), ('44', 'Microsoft Azure'), ('45', 'Google Cloud Platform (GCP)'), ('46', 'WordPress'), ('47', 'Drupal'), ('48', 'Joomla'), ('49', 'Magento'), ('50', 'Salesforce'), ('51', 'Shopify'), ('52', 'WooCommerce'), ('53', 'Squarespace'), ('54', 'Wix'), ('55', 'Weebly'), ('56', 'Blogger'), ('57', 'Ghost'), ('58', 'Medium'), ('59', 'Tumblr')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='core.post')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='project_images', to='core.image'),
        ),
    ]
