# Generated by Django 4.1.1 on 2023-06-14 20:04

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_project_technologies_remove_project_tools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='frameworks',
            field=core.models.CustomMultiSelectField(blank=True, choices=[('1', 'Django'), ('2', 'Flask'), ('3', 'React'), ('4', 'Angular'), ('5', 'Vue'), ('6', 'Laravel'), ('7', 'Spring'), ('8', 'Express'), ('9', 'Django Rest Framework'), ('10', 'Flutter'), ('11', 'React Native'), ('12', 'Ionic'), ('13', 'Xamarin'), ('14', 'Electron'), ('15', 'HUGO'), ('16', 'Gatsby'), ('17', 'Next.js'), ('18', 'Nuxt.js'), ('19', 'Jekyll'), ('20', 'Ruby on Rails'), ('21', 'ASP.NET'), ('22', 'ASP.NET Core'), ('23', 'Spring Boot'), ('24', 'Express.js'), ('25', 'Vue.js'), ('26', 'AngularJS'), ('27', 'Ember.js'), ('28', 'MeteorJS'), ('29', 'CakePHP'), ('30', 'CodeIgniter'), ('31', 'Zend Framework'), ('32', 'Yii'), ('33', 'Symfony'), ('34', 'Phalcon'), ('35', 'Vite.js'), ('36', 'Svelte'), ('37', 'Quasar'), ('38', 'Tailwind CSS'), ('39', 'Bootstrap'), ('40', 'Materialize'), ('41', 'Bulma'), ('42', 'Foundation'), ('43', 'Semantic UI'), ('44', 'UIKit'), ('45', 'Ant Design'), ('46', 'Chakra UI'), ('47', 'Tailwind UI'), ('48', 'PrimeReact')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frameworks',
            field=core.models.CustomMultiSelectField(blank=True, choices=[('1', 'Django'), ('2', 'Flask'), ('3', 'React'), ('4', 'Angular'), ('5', 'Vue'), ('6', 'Laravel'), ('7', 'Spring'), ('8', 'Express'), ('9', 'Django Rest Framework'), ('10', 'Flutter'), ('11', 'React Native'), ('12', 'Ionic'), ('13', 'Xamarin'), ('14', 'Electron'), ('15', 'HUGO'), ('16', 'Gatsby'), ('17', 'Next.js'), ('18', 'Nuxt.js'), ('19', 'Jekyll'), ('20', 'Ruby on Rails'), ('21', 'ASP.NET'), ('22', 'ASP.NET Core'), ('23', 'Spring Boot'), ('24', 'Express.js'), ('25', 'Vue.js'), ('26', 'AngularJS'), ('27', 'Ember.js'), ('28', 'MeteorJS'), ('29', 'CakePHP'), ('30', 'CodeIgniter'), ('31', 'Zend Framework'), ('32', 'Yii'), ('33', 'Symfony'), ('34', 'Phalcon'), ('35', 'Vite.js'), ('36', 'Svelte'), ('37', 'Quasar'), ('38', 'Tailwind CSS'), ('39', 'Bootstrap'), ('40', 'Materialize'), ('41', 'Bulma'), ('42', 'Foundation'), ('43', 'Semantic UI'), ('44', 'UIKit'), ('45', 'Ant Design'), ('46', 'Chakra UI'), ('47', 'Tailwind UI'), ('48', 'PrimeReact')], max_length=255, null=True),
        ),
    ]
