# Generated by Django 4.1.1 on 2023-06-14 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_frameworks_alter_project_frameworks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technology',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tool',
            name='project',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
